"use client";

import "./globals.css";

import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const client = new ApolloClient({
  uri: "http://localhost:3001/api/graphql",
  cache: new InMemoryCache(),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full h-full ">
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
